In [1]:
import json
import pandas as pd

In [2]:
with open("../data/raw/tmdb_major_movies.json", "r") as f:
    major_tmdb= json.load(f)

In [3]:
major_df = pd.DataFrame(major_tmdb)
major_df.head()

,id,title,imdb_id,release_date,production_companies,budget,revenue,vote_average,vote_count
0,475557,Joker,tt7286456,2019-10-01,"[{'id': 174, 'logo_path': '/zhD3hhtKB5qyv7ZeL4...",55000000,1078958629,8.122,27972
1,76341,Mad Max: Fury Road,tt1392190,2015-05-13,"[{'id': 174, 'logo_path': '/zhD3hhtKB5qyv7ZeL4...",150000000,378858340,7.635,24294
2,297761,Suicide Squad,tt1386697,2016-08-03,"[{'id': 174, 'logo_path': '/zhD3hhtKB5qyv7ZeL4...",175000000,749200054,5.917,22234
3,135397,Jurassic World,tt0369610,2015-06-06,"[{'id': 56, 'logo_path': '/cEaxANEisCqeEoRvODv...",150000000,1671537444,6.703,21727
4,297762,Wonder Woman,tt0451279,2017-05-30,"[{'id': 507, 'logo_path': '/aRmHe6GWxYMRCQljF7...",149000000,823970682,7.207,21027

In [4]:
major_df = major_df.drop(["production_companies","id"], axis=1)
major_df.head()

,title,imdb_id,release_date,budget,revenue,vote_average,vote_count
0,Joker,tt7286456,2019-10-01,55000000,1078958629,8.122,27972
1,Mad Max: Fury Road,tt1392190,2015-05-13,150000000,378858340,7.635,24294
2,Suicide Squad,tt1386697,2016-08-03,175000000,749200054,5.917,22234
3,Jurassic World,tt0369610,2015-06-06,150000000,1671537444,6.703,21727
4,Wonder Woman,tt0451279,2017-05-30,149000000,823970682,7.207,21027

In [5]:
major_df["studio_type"]="major"
major_df.head()

,title,imdb_id,release_date,budget,revenue,vote_average,vote_count,studio_type
0,Joker,tt7286456,2019-10-01,55000000,1078958629,8.122,27972,major
1,Mad Max: Fury Road,tt1392190,2015-05-13,150000000,378858340,7.635,24294,major
2,Suicide Squad,tt1386697,2016-08-03,175000000,749200054,5.917,22234,major
3,Jurassic World,tt0369610,2015-06-06,150000000,1671537444,6.703,21727,major
4,Wonder Woman,tt0451279,2017-05-30,149000000,823970682,7.207,21027,major

Same for indie company

In [6]:
with open("../data/raw/tmdb_indie_movies.json", "r") as f:
    indie_movies = json.load(f)

indie_df = pd.DataFrame(indie_movies)
indie_df = indie_df.drop(["production_companies","id"], axis=1)
indie_df["studio_type"] = "indie"
indie_df.head()

,title,imdb_id,release_date,budget,revenue,vote_average,vote_count,studio_type
0,Deadpool,tt1431045,2016-02-09,58000000,782837347,7.624,32966,indie
1,Avengers: Infinity War,tt4154756,2018-04-25,300000000,2052415039,8.200,32384,indie
2,Avengers: Endgame,tt4154796,2019-04-24,356000000,2799439100,8.239,28126,indie
3,Avengers: Age of Ultron,tt2395427,2015-04-22,235000000,1405403694,7.275,24663,indie
4,Captain America: Civil War,tt3498820,2016-04-27,250000000,1155046416,7.450,24210,indie

把indie和major拼起来

In [7]:
tmdb_df = pd.concat(
    [major_df,indie_df],
    ignore_index = True
)
tmdb_df.head()
tmdb_df.tail()

,title,imdb_id,release_date,budget,revenue,vote_average,vote_count,studio_type
872,Elle,tt3716530,2016-05-25,9800000,2341534,6.639,2014,indie
873,Capernaum,tt8267604,2018-09-20,4000000,64978931,8.150,2007,indie
874,Colonia,tt4005402,2016-02-12,14000000,3621046,7.255,2006,indie
875,Ballerina,tt2261287,2016-12-14,30000000,109573511,7.204,2004,indie
876,Miss Sloane,tt4540710,2016-11-25,13000000,9101546,7.405,2000,indie

In [8]:
tmdb_df.dtypes

title               str
imdb_id             str
release_date        str
budget            int64
revenue           int64
vote_average    float64
vote_count        int64
studio_type         str
dtype: object

In [9]:
tmdb_df.shape

(877, 8)

In [10]:
tmdb_df.to_csv("../data/processed/tmdb_movies.csv",index=False)